### ISSUE TITLE
更新後の画面遷移について

### ISSUE THREAD

**Issue by onishi024** [imim10042/red-muffin-master#9]
案件詳細画面の更新後に案件一覧に遷移するのってUI的にどうなんすかね。。
案件登録はそれ以上そこの画面に居ても意味ない＝案件一覧に行かないと更新された内容を確認できないのに対し、案件詳細画面の更新結果は案件一覧に行っちゃったら見えないもんね。
ユーザ的には、ちょっとずつ更新して確定しつつ計画書いて行きたい人もいるのでは。

**Comment by imim10042** [comment]
α版開発の中でついでに取り込みました。
https://trello.com/c/FFnCG5ye
